// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package queryprint

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tEOF-0]
	_ = x[tAND-1]
	_ = x[tBANG_EQUAL-2]
	_ = x[tCOMMA-3]
	_ = x[tDOT-4]
	_ = x[tEQUAL-5]
	_ = x[tEQUAL_EQUAL-6]
	_ = x[tGREATER-7]
	_ = x[tGREATER_EQUAL-8]
	_ = x[tIDENTIFIER-9]
	_ = x[tLEFT_PAREN-10]
	_ = x[tLESS-11]
	_ = x[tLESS_EQUAL-12]
	_ = x[tLIKE-13]
	_ = x[tMINUS-14]
	_ = x[tNOT-15]
	_ = x[tOR-16]
	_ = x[tPERCENT-17]
	_ = x[tPIPE-18]
	_ = x[tPLUS-19]
	_ = x[tQUOTED_FIELD-20]
	_ = x[tRIGHT_PAREN-21]
	_ = x[tSLASH-22]
	_ = x[tSPACE-23]
	_ = x[tSTAR-24]
	_ = x[tSTRING-25]
	_ = x[tXOR-26]
}

const _tokenType_name = "tEOFtANDtBANG_EQUALtCOMMAtDOTtEQUALtEQUAL_EQUALtGREATERtGREATER_EQUALtIDENTIFIERtLEFT_PARENtLESStLESS_EQUALtLIKEtMINUStNOTtORtPERCENTtPIPEtPLUStQUOTED_FIELDtRIGHT_PARENtSLASHtSPACEtSTARtSTRINGtXOR"

var _tokenType_index = [...]uint8{0, 4, 8, 19, 25, 29, 35, 47, 55, 69, 80, 91, 96, 107, 112, 118, 122, 125, 133, 138, 143, 156, 168, 174, 180, 185, 192, 196}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
